package com.mycompany.miniproject;



import java.awt.Color;
import java.util.ArrayList;
import javax.swing.*;

import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;


/**
 *
 * @author riham
 */
public class Main_Home extends javax.swing.JFrame {
 //   public  static institution Esi;
    public static ArrayList<TP_Salle> salles = new ArrayList<>();
public static ArrayList<TP_Salle> s1 = new ArrayList<>();
public static ArrayList<TP_Salle> s2 = new ArrayList<>();
    static int Current_Salle_TP_Index;
    static public DefaultTableModel model;
 
   // public static void institution_init(){
   static Block B= new Block("A","b", "white");
    static ArrayList<Block> Blocks = new ArrayList<Block>();
     
   static department Second_cycle = new department(0,"second cycle","code","Amrane","contact_sc@esi-sba.dz",Blocks);
   static department preparatory_cycle = new department(1,"preparatory cycle","code","Ased","contact_pc@esi-sba.dz",Blocks);
   
    static department [] departements= { preparatory_cycle,Second_cycle};
  
   public  static institution Esi = new institution(0,"hight school"," 5 mai sidi Bel-Abbes","0000000","logo",departements);
    
   // }
    public static void TP_Salles_init(){
        salles.clear();
        TP_Salle  Salle_TP = new TP_Salle (1,"Salle TP1",222,15,"15",null);
        salles.add(Salle_TP);
        s1.clear(); 
        s1.add(Salle_TP);
        TP_Salle  Salle_TP1 = new TP_Salle (1,"Salle TP1",222,15,"15",null);
        s2.clear(); 
        s2.add(Salle_TP1);
    }
    public void selected_TPS(int i){
        if (i==0){
            salles=s1;
        }
        else
          salles=s2;  
     //  salles=Esi.getDep()[i].getBlocks().get(0).getBuildings();
    }
    public static void load_Departements(){
    DefaultComboBoxModel<String> l = new DefaultComboBoxModel<>();
       for (department dep : Esi.getDep()) {
            l.addElement(dep.getDepartementName());
        }
    
   DepartementCompobox.setModel(l);
     



    
    }
    public static void load_Salles(ArrayList<TP_Salle> salles){
    
     DefaultListModel<String> listModel = new DefaultListModel<String>();
     
        for (TP_Salle item : salles) {
            listModel.addElement(item.building_name);
        }

    TP_Salles_Jlist.setModel(listModel);
        
    }
     
      
      
   
   
  
    public static void print_salle_materials(ArrayList<Materials> tp_materials){
        
      model =(DefaultTableModel) Material_table_Affiche.getModel();
      model.setRowCount(0);
       ArrayList<Materials> list =tp_materials;
       Object rowData []=new Object[4];
     for (int i=0;i<=list.size();i++){
       rowData[0]=list.get(i).registeration_number;
       rowData[1]=list.get(i).date_installion;
      
       String r=null;
       switch(list.get(i).id+1){
          case 1:
               r="PC";
               break;
          case 2:
              r="Datashow";
              break;
          case 3:
              r="Printer";
              break;
          case 4:
              r="Accessoires";
              break;
       }
      rowData[3]=r;
      model.addRow(rowData);
     }
  
     
    
    }  
    //DepartementCompobox.getSelectedIndex()
    
    /**
     * Creates new form Main_Home
     */
    public Main_Home(){
        
    initComponents(); 
    setTitle("My JFrame");

        // Set the size of the JFrame
        

        // Set the background color of the JFrame
        getContentPane().setBackground(Color.WHITE);

        // Show the JFrame
        setVisible(true);

        // Set the default close operation of the JFrame
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    
    TP_Salles_init();
//    institution_init();
    load_Departements();
    this.setLocationRelativeTo(null);
    load_Salles( salles);
   
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Material_table_Affiche = new javax.swing.JTable();
        Add_new_material = new javax.swing.JButton();
        Delete_selected_material = new javax.swing.JButton();
        Delete_TP_Salle = new javax.swing.JButton();
        Creat_TP_Salle = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TP_Salles_Jlist = new javax.swing.JList<>();
        DepartementCompobox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Dep_name_label = new javax.swing.JLabel();
        Dep_code_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Dep_head_label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Dep_email_label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Dep_services_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Material_table_Affiche.setBackground(new java.awt.Color(255, 218, 184));
        Material_table_Affiche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration number", "Installistion Date", "Name/cpu/ram ", "Type"
            }
        ));
        jScrollPane1.setViewportView(Material_table_Affiche);

        Add_new_material.setBackground(new java.awt.Color(249, 134, 74));
        Add_new_material.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        Add_new_material.setText("Add new material");
        Add_new_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_new_materialMouseClicked(evt);
            }
        });
        Add_new_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_new_materialActionPerformed(evt);
            }
        });

        Delete_selected_material.setBackground(new java.awt.Color(249, 134, 74));
        Delete_selected_material.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        Delete_selected_material.setText("Delete selected material");
        Delete_selected_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_selected_materialActionPerformed(evt);
            }
        });

        Delete_TP_Salle.setBackground(new java.awt.Color(249, 134, 74));
        Delete_TP_Salle.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        Delete_TP_Salle.setText("- Delete TP Salle");
        Delete_TP_Salle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_TP_SalleMouseClicked(evt);
            }
        });
        Delete_TP_Salle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_TP_SalleActionPerformed(evt);
            }
        });

        Creat_TP_Salle.setBackground(new java.awt.Color(249, 134, 74));
        Creat_TP_Salle.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        Creat_TP_Salle.setText("+ Creat TP Salle");
        Creat_TP_Salle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Creat_TP_SalleActionPerformed(evt);
            }
        });

        TP_Salles_Jlist.setBackground(new java.awt.Color(248, 199, 173));
        TP_Salles_Jlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TP_Salles_JlistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TP_Salles_Jlist);

        DepartementCompobox.setBackground(new java.awt.Color(249, 134, 74));
        DepartementCompobox.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        DepartementCompobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Selected departement", "preparatory cycle", "Second cycle" }));
        DepartementCompobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartementCompoboxActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(248, 199, 173));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Depatement Information");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel3.setText("Code :");

        Dep_name_label.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        Dep_name_label.setText("Name :");

        Dep_code_label.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        Dep_code_label.setText("Code :");

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel6.setText("Head of the departement :");

        Dep_head_label.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        Dep_head_label.setText("Head of the departement :");

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel8.setText("Email adress:");

        Dep_email_label.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        Dep_email_label.setText("Email adress:");

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel10.setText("Number of Services :");

        Dep_services_label.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        Dep_services_label.setText("Number of Services :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dep_services_label))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(Dep_code_label))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dep_name_label)))
                                .addGap(8, 8, 8)
                                .addComponent(Dep_head_label))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dep_email_label))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Dep_name_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dep_code_label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Dep_head_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Dep_email_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Dep_services_label))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("All material");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepartementCompobox, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Creat_TP_Salle, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Delete_TP_Salle, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Add_new_material, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(Delete_selected_material, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(179, 179, 179)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(DepartementCompobox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Creat_TP_Salle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_TP_Salle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_new_material, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_selected_material, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_new_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_new_materialActionPerformed
        // TODO add your handling code here:
       

       
    }//GEN-LAST:event_Add_new_materialActionPerformed

    private void Delete_selected_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_selected_materialActionPerformed
        // TODO add your handling code here:
       int selectedRow = Material_table_Affiche.getSelectedRow();
    DefaultTableModel model = (DefaultTableModel) Material_table_Affiche.getModel();
    model.removeRow(selectedRow);
    
    salles.get(Current_Salle_TP_Index).getMaterials().remove(selectedRow);
    }//GEN-LAST:event_Delete_selected_materialActionPerformed

    private void DepartementCompoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartementCompoboxActionPerformed
        // TODO add your handling code here:
       int selectedIndex = DepartementCompobox.getSelectedIndex();
   selected_TPS(selectedIndex);
       Dep_services_label.setText("4");
       
        department[] d = Esi.getDep();
        Dep_name_label.setText(d[selectedIndex].getDepartementName());
        Dep_code_label.setText(d[selectedIndex].getCode());
        Dep_head_label.setText(d[selectedIndex].getHeadname());
        Dep_email_label.setText(d[selectedIndex].getEmail_address());
       
        load_Salles( salles);
       

       
    }//GEN-LAST:event_DepartementCompoboxActionPerformed

    private void Creat_TP_SalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Creat_TP_SalleActionPerformed
        // TODO add your handling code here:
        AddSalleTP frame2 = new   AddSalleTP();
        frame2.setDefaultCloseOperation(PROPERTIES);
      frame2.setVisible(true);
        
    }//GEN-LAST:event_Creat_TP_SalleActionPerformed

    private void TP_Salles_JlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TP_Salles_JlistMouseClicked
        // TODO add your handling code here:
        int selectedTp_salle =-1;
        
        selectedTp_salle= TP_Salles_Jlist.getSelectedIndex();
        this.Current_Salle_TP_Index=selectedTp_salle;

        if (selectedTp_salle != -1){

            ArrayList<Materials> tp_materials=salles.get(selectedTp_salle).getMaterials();
            print_salle_materials(tp_materials);
 
        }
    }//GEN-LAST:event_TP_Salles_JlistMouseClicked

    private void Add_new_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_new_materialMouseClicked
        // TODO add your handling code here:
        
      new AddMaterial_tp(Current_Salle_TP_Index).setVisible(true);
    }//GEN-LAST:event_Add_new_materialMouseClicked

    private void Delete_TP_SalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_TP_SalleMouseClicked
        // TODO add your handling code here:
        
        Current_Salle_TP_Index= TP_Salles_Jlist.getSelectedIndex();
        salles.remove( Current_Salle_TP_Index);
        load_Salles( salles);
             int selectedRow = Material_table_Affiche.getSelectedRow();
                     Main_Home.print_salle_materials (null);
 
        
    }//GEN-LAST:event_Delete_TP_SalleMouseClicked

    private void Delete_TP_SalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_TP_SalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_TP_SalleActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_new_material;
    private javax.swing.JButton Creat_TP_Salle;
    private javax.swing.JButton Delete_TP_Salle;
    private javax.swing.JButton Delete_selected_material;
    public javax.swing.JLabel Dep_code_label;
    public static javax.swing.JLabel Dep_email_label;
    public javax.swing.JLabel Dep_head_label;
    public javax.swing.JLabel Dep_name_label;
    public javax.swing.JLabel Dep_services_label;
    private static javax.swing.JComboBox<String> DepartementCompobox;
    public static javax.swing.JTable Material_table_Affiche;
    private static javax.swing.JList<String> TP_Salles_Jlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
